// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm-FxOhLnJwAEZtuygxg_V18zG29O5D1A',
    appId: '1:274694458377:web:975a8bc0da6f4034bebcd8',
    messagingSenderId: '274694458377',
    projectId: 'flutter-demo-3743c',
    authDomain: 'flutter-demo-3743c.firebaseapp.com',
    storageBucket: 'flutter-demo-3743c.appspot.com',
    measurementId: 'G-KH1W4JCMRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjsXTOIBrQtkiV-GYl2u9gi_B0w-d0b0Y',
    appId: '1:274694458377:android:d37e9701b8329e10bebcd8',
    messagingSenderId: '274694458377',
    projectId: 'flutter-demo-3743c',
    storageBucket: 'flutter-demo-3743c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMRGYtOTH8q-j4Sovbej2phhdbitzjmdU',
    appId: '1:274694458377:ios:73d6e79a4587f440bebcd8',
    messagingSenderId: '274694458377',
    projectId: 'flutter-demo-3743c',
    storageBucket: 'flutter-demo-3743c.appspot.com',
    iosClientId: '274694458377-f0t4pa0j3kofnjcpem880h89c9eers15.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.demo.flutterDemo',
  );
}
